name: twitch-helpers
org: wolfstar
install: true
packagePath: packages/twitch-helpers
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: wolfstar-project/stars-components
gitHostVariant: github
