name: '*next*'
package:
    - '@wolfstar/env-utilities'
    - '@wolfstar/http-framework'
    - '@wolfstar/http-framework-i18n'
    - '@wolfstar/i18next-backend'
    - '@wolfstar/i18next-type-generator'
    - '@wolfstar/influx-utilities'
    - '@wolfstar/logger'
    - '@wolfstar/reddit-helpers'
    - '@wolfstar/safe-fetch'
    - '@wolfstar/shared-http-pieces'
    - '@wolfstar/shared-influx-pieces'
    - '@wolfstar/start-banner'
    - '@wolfstar/twitch-helpers'
    - '@wolfstar/weather-helpers'
