packages:
    - 'packages/*'

autoInstallPeers: true

dedupePeers: true

linkWorkspacePackages: true

preferWorkspacePackages: true

strictPeerDependencies: false

overrides:
    '@types/pg': '8.15.6'
    ansi-regex: '^5.0.1'
    minimist: '1.2.8'

allowBuilds:
    '@swc/core': true
    esbuild: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - '@redstardev/*'
    - unrun@0.3.1
