packages:
    - 'packages/*'
    - 'examples/*'

autoInstallPeers: true

dedupePeers: true

linkWorkspacePackages: true

preferWorkspacePackages: true

strictPeerDependencies: false

allowBuilds:
    '@swc/core': true
    esbuild: true
    sharp: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - '@redstardev/*'
    - '@wolfstar/plugin-i18next@1.0.0'
    - unrun@0.3.1
    - vitepress@2.0.0-alpha.18
    - '@shikijs/vitepress-twoslash@4.3.1'
    - vitepress-plugin-group-icons@1.7.5
    - vitepress-plugin-llms@1.13.3
    - markdown-it-image-size@15.0.1
    - vite@6.4.3
    - '@wolfstar/plugin-i18next@1.0.1-next-20260830111821'
