import type { Rule } from 'eslint';

const i18nextPackages = ['@wolfstar/plugin-i18next', '@wolfstar/http-framework-i18n'];
const translateFactories = ['getSupportedUserLanguageT', 'getSupportedLanguageT', 'fetchT'];

interface MaybeNode {
	type: string;
	value?: unknown;
	expressions?: unknown[];
}

/**
 * Determines whether a node is a statically known string, i.e. a string literal or a template literal without
 * interpolation.
 *
 * @param node - The node to inspect.
 * @returns Whether the key can be resolved statically.
 */
function isStaticKey(node: MaybeNode | undefined): boolean {
	if (!node) return true;
	if (node.type === 'Literal') return typeof node.value === 'string';
	if (node.type === 'TemplateLiteral') return (node.expressions ?? []).length === 0;
	return false;
}

/**
 * Requires translation keys to be written as string literals.
 *
 * Keys are typed through the `CustomTypeOptions` augmentation generated by `@wolfstar/i18next-type-generator`; a
 * dynamically built key silently opts out of that type checking, so a typo or a removed key only surfaces at runtime.
 */
const rule: Rule.RuleModule = {
	meta: {
		type: 'problem',
		docs: {
			description: 'require i18next translation keys to be string literals so generated key types apply',
			recommended: true
		},
		messages: {
			dynamicKey:
				'Translation keys must be string literals; a computed key bypasses the generated i18next key types, so typos and removed keys are only caught at runtime.'
		},
		schema: []
	},
	create(context) {
		let importsI18next = false;
		const factoryBindings = new Set<string>();
		const translateBindings = new Set<string>();
		let localizedBuilderName: string | null = null;

		return {
			ImportDeclaration(node) {
				const source = (node.source as { value?: unknown }).value;
				if (typeof source !== 'string' || !i18nextPackages.includes(source)) return;

				importsI18next = true;
				for (const specifier of node.specifiers) {
					if (specifier.type !== 'ImportSpecifier') continue;

					const imported = (specifier.imported as { name?: string }).name;
					if (imported === 'applyLocalizedBuilder') localizedBuilderName = specifier.local.name;
					if (imported !== undefined && translateFactories.includes(imported)) factoryBindings.add(specifier.local.name);
				}
			},
			VariableDeclarator(node) {
				if (!node.init || node.init.type !== 'CallExpression') return;

				const callee = node.init.callee as { type: string; name?: string };
				if (callee.type !== 'Identifier' || callee.name === undefined) return;
				if (!factoryBindings.has(callee.name)) return;
				if (node.id.type !== 'Identifier') return;

				translateBindings.add(node.id.name);
			},
			CallExpression(node) {
				if (!importsI18next) return;

				const callee = node.callee as { type: string; name?: string };
				if (callee.type !== 'Identifier' || callee.name === undefined) return;

				if (callee.name === localizedBuilderName) {
					for (const argument of node.arguments.slice(1, 3)) {
						if (!isStaticKey(argument as MaybeNode)) {
							context.report({ node: argument as never, messageId: 'dynamicKey' });
						}
					}

					return;
				}

				if (!translateBindings.has(callee.name)) return;

				const [key] = node.arguments;
				if (key && !isStaticKey(key as MaybeNode)) {
					context.report({ node: key as never, messageId: 'dynamicKey' });
				}
			}
		};
	}
};

export default rule;
