// This file is automatically generated, do not edit it.
/* eslint-disable */
/* oxlint-disable */
// oxfmt-ignore
// prettier-ignore
import "i18next";

// oxfmt-ignore
// prettier-ignore
declare module "i18next" {
  interface CustomTypeOptions {
    resources: {
      "commands/shared": {
        infoName: "info";
        infoDescription: "Provides information about me, and links for adding the bot and joining the support server";
        infoFieldUptimeTitle: "Uptime";
        infoFieldUptimeValue: "• **Host**: {{host}}\n• **Client**: {{client}}";
        infoFieldServerUsageTitle: "Server Usage";
        infoFieldServerUsageValue: "• **CPU Usage**: {{cpu}}\n• **Memory**: {{heapUsed}}MB (Total: {{heapTotal}}MB)";
        infoButtonInvite: "Add me to your server!";
        infoButtonSupport: "Support server";
        infoButtonGitHub: "GitHub Repository";
        infoButtonDonate: "Donate";
      };
    } & CustomResources;
  }

  interface CustomResources {}
}
