name: i18next-backend
org: wolfstar
install: true
packagePath: packages/i18next-backend
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: wolfstar-project/stars-components
gitHostVariant: github
