name: http-framework
org: wolfstar
install: true
packagePath: packages/http-framework
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: wolfstar-project/stars-components
gitHostVariant: github
