import { annotateGeneratedFile } from '../src/generate.js';

const formatted = ["import 'i18next';", '', "declare module 'i18next' {", '\tinterface CustomTypeOptions {}', '}', ''].join('\n');

describe('annotateGeneratedFile', () => {
	test('GIVEN formatted source THEN prepends the generated file header', () => {
		const result = annotateGeneratedFile(formatted);

		expect(
			result.startsWith(['// This file is automatically generated, do not edit it.', '/* eslint-disable */', '/* oxlint-disable */'].join('\n'))
		).toBe(true);
	});

	test('GIVEN formatted source THEN inserts formatter ignores before the import statement', () => {
		const result = annotateGeneratedFile(formatted);

		expect(result).toContain(['// oxfmt-ignore', '// prettier-ignore', "import 'i18next';"].join('\n'));
	});

	test('GIVEN formatted source THEN inserts formatter ignores before the declare module statement', () => {
		const result = annotateGeneratedFile(formatted);

		expect(result).toContain(['// oxfmt-ignore', '// prettier-ignore', "declare module 'i18next' {"].join('\n'));
	});
});
