import type { CommandData } from '../src/dev/bridge.js';
import { generateCommandTypes } from '../src/utils/command-types.js';

const HEADER = `// This file is automatically generated by \`stars codegen\`, do not edit it.
/* eslint-disable */
/* oxlint-disable */
// oxfmt-ignore
// prettier-ignore
`;

const BLOCK = (entries: string) => `// oxfmt-ignore
// prettier-ignore
declare module '@wolfstar/http-framework' {
  interface CommandOptionsRegistry {
${entries}  }
}
`;

const generate = (...global: CommandData[]) => generateCommandTypes({ global, guilds: {} });

describe('generateCommandTypes', () => {
	test('writes an empty registry for a project without commands', () => {
		expect(generate()).toBe(`${HEADER}export {};\n\n${BLOCK('')}`);
	});

	test('maps every option type to what the framework resolves it to', () => {
		const output = generate({
			name: 'everything',
			options: [
				{ type: 3, name: 'text', required: true },
				{ type: 4, name: 'count' },
				{ type: 10, name: 'ratio' },
				{ type: 5, name: 'flag' },
				{ type: 6, name: 'who', required: true },
				{ type: 8, name: 'role' },
				{ type: 9, name: 'target' },
				{ type: 11, name: 'file' },
				{ type: 7, name: 'where' }
			]
		});

		expect(output).toBe(`${HEADER}import type { TransformedArguments } from '@wolfstar/http-framework';

${BLOCK(`    'everything': {
      count?: number;
      file?: TransformedArguments.Attachment;
      flag?: boolean;
      ratio?: number;
      role?: TransformedArguments.Role;
      target?: TransformedArguments.Mentionable;
      text: string;
      where?: TransformedArguments.Channel;
      who: TransformedArguments.User;
    };
`)}`);
	});

	test('narrows choices to a literal union', () => {
		const output = generate({
			name: 'subscribe',
			options: [
				{
					type: 3,
					name: 'type',
					required: true,
					choices: [
						{ name: 'Live', value: 'live' },
						{ name: 'Offline', value: 'offline' }
					]
				},
				{
					type: 4,
					name: 'level',
					choices: [
						{ name: 'One', value: 1 },
						{ name: 'Two', value: 2 },
						{ name: 'Again', value: 2 }
					]
				},
				{
					type: 10,
					name: 'ratio',
					choices: [
						{ name: 'Half', value: 0.5 },
						{ name: 'Negative', value: -1 }
					]
				}
			]
		});

		expect(output).toContain('      level?: 1 | 2;');
		expect(output).toContain("      type: 'live' | 'offline';");
		expect(output).toContain('      ratio?: 0.5 | -1;');
	});

	test('escapes choices and quotes names that are not identifiers', () => {
		const output = generate({
			name: 'odd-name',
			options: [{ type: 3, name: 'my-option', required: true, choices: [{ name: 'quote', value: "it's \\ a\nvalue" }] }]
		});

		expect(output).toContain("    'odd-name': {");
		expect(output).toContain("      'my-option': 'it\\'s \\\\ a\\nvalue';");
	});

	test('narrows a channel to its channel types, sorted and without duplicates', () => {
		const output = generate({ name: 'move', options: [{ type: 7, name: 'to', required: true, channel_types: [5, 0, 5] }] });

		expect(output).toContain("      to: TransformedArguments.Channel & { type: Extract<TransformedArguments.Channel['type'], 0 | 5> };");
	});

	test('keeps a command without options and skips the context menu ones', () => {
		const output = generate({ name: 'ping' }, { name: 'Report', type: 3 }, { name: 'Profile', type: 2 }, { name: 'launch', type: 4 });

		expect(output).toBe(`${HEADER}export {};\n\n${BLOCK("    'ping': {};\n")}`);
	});

	test('writes one entry per subcommand and per subcommand of a group', () => {
		const output = generate({
			name: 'subscriptions',
			options: [
				{ type: 1, name: 'list' },
				{
					type: 2,
					name: 'twitch',
					options: [
						{ type: 1, name: 'add', options: [{ type: 3, name: 'streamer', required: true, autocomplete: true }] },
						{ type: 1, name: 'remove', options: [{ type: 3, name: 'streamer', required: true }] }
					]
				}
			]
		} as CommandData);

		expect(output).toBe(`${HEADER}export {};

${BLOCK(`    'subscriptions list': {};
    'subscriptions twitch add': {
      streamer: string;
    };
    'subscriptions twitch remove': {
      streamer: string;
    };
`)}`);
	});

	test('covers a command built by a loop, the way ring builds config set', () => {
		const limits = ['maxMessages', 'maxEmbeds', 'maxAttachments'];
		const options = [{ type: 3, name: 'guild', required: true }, ...limits.map((name) => ({ type: 4, name }))];

		const output = generate({ name: 'config', options: [{ type: 1, name: 'set', options }] } as CommandData);

		expect(output).toContain(`    'config set': {
      guild: string;
      maxAttachments?: number;
      maxEmbeds?: number;
      maxMessages?: number;
    };`);
	});

	test('uses the default name of a localized command', () => {
		const output = generate({
			name: 'ping',
			name_localizations: { it: 'pong' },
			options: [{ type: 3, name: 'text', name_localizations: { it: 'testo' } }]
		});

		expect(output).toContain("'ping': {\n      text?: string;");
		expect(output).not.toContain('pong');
		expect(output).not.toContain('testo');
	});

	test('does not depend on the order of the commands or options, and keeps the first of a path', () => {
		const a = {
			name: 'alpha',
			options: [
				{ type: 3, name: 'b' },
				{ type: 3, name: 'a' }
			]
		} as CommandData;
		const b = { name: 'beta', options: [{ type: 5, name: 'x' }] } as CommandData;
		const repeated = { name: 'alpha', options: [{ type: 5, name: 'other' }] } as CommandData;

		const forward = generateCommandTypes({ global: [a, b], guilds: { '2': [repeated], '1': [b] } });
		const backward = generateCommandTypes({ global: [b, { ...a, options: [...a.options!].reverse() } as CommandData], guilds: { '1': [b] } });

		expect(forward).toBe(backward);
		expect(forward.indexOf("'alpha'")).toBeLessThan(forward.indexOf("'beta'"));
		expect(forward).not.toContain('other');
	});

	test('reads commands that are only registered for a guild', () => {
		const output = generateCommandTypes({
			global: [],
			guilds: { '1': [{ name: 'admin', options: [{ type: 6, name: 'user', required: true }] }] }
		});

		expect(output).toContain("    'admin': {\n      user: TransformedArguments.User;");
	});

	test('gives an option type it does not know about the unknown type', () => {
		expect(generate({ name: 'future', options: [{ type: 99, name: 'later' }] })).toContain('      later?: unknown;');
	});
});
