name: influx-utilities
org: wolfstar
install: true
packagePath: packages/influx-utilities
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: wolfstar-project/stars-components
gitHostVariant: github
