// Structurally the same as `BooleanString`, `IntegerString` and `NumberString` from `./types`, declared here so that the
// `@wolfstar/env-utilities/varlock` entry does not share a declaration chunk with `Env` (a chunk breaks the
// `IntegerString` lookup inside a `declare module '@wolfstar/env-utilities'` augmentation).
type BooleanString = 'true' | 'false';
type IntegerString = `${bigint}`;
type NumberString = `${number}`;

/**
 * Maps one value type of varlock's generated `CoercedEnvSchema` to the string form `process.env` holds, as
 * understood by the `envParse*` functions.
 *
 * - `boolean` becomes {@link BooleanString}.
 * - `number` becomes a string that is both an {@link IntegerString} and a {@link NumberString}: the coerced type
 *   cannot tell an integer from a float (and `port` is a number), so the key is accepted by `envParseInteger` and
 *   `envParseNumber` alike.
 * - `string` and `enum` (a union of string literals) are kept as they are.
 */
export type EnvValueFromVarlock<V> = V extends boolean
	? BooleanString
	: V extends number
		? IntegerString & NumberString
		: V extends string
			? V
			: V extends null | undefined
				? undefined
				: string;

/**
 * Derives the `Env` entries of an application from the `CoercedEnvSchema` type that varlock generates with
 * `@generateTsTypes`, so the schema stays the only place where a variable is declared. Optional keys stay optional.
 *
 * @example
 * ```typescript
 * // env.d.ts is generated by varlock and exports `CoercedEnvSchema`
 * import type { CoercedEnvSchema } from './env';
 * import type { EnvFromVarlock } from '@wolfstar/env-utilities/varlock';
 *
 * declare module '@wolfstar/env-utilities' {
 * 	interface Env extends EnvFromVarlock<CoercedEnvSchema> {}
 * }
 * ```
 */
export type EnvFromVarlock<T> = { [K in keyof T]: EnvValueFromVarlock<T[K]> };
