import { gray, green, italic, yellow } from 'colorette';
import { mkdir, opendir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { inspect } from 'node:util';

const ci = 'CI' in process.env && process.env.CI !== 'false';

const FileIcon = ci ? '📄' : '\uE628';
const DirectoryIcon = ci ? '📂' : '\uF413';

const GENERATED_FILE_HEADER = ['// This file is automatically generated, do not edit it.', '/* eslint-disable */', '/* oxlint-disable */'] as const;

const FORMATTER_IGNORE = ['// oxfmt-ignore', '// prettier-ignore'] as const;

/**
 * Inject formatter and linter ignore directives into the already-formatted output.
 *
 * The file-level `eslint-disable` / `oxlint-disable` comments suppress all lint rules, while the
 * per-statement `oxfmt-ignore` / `prettier-ignore` comments protect the two top-level statements
 * (the `i18next` import and the `declare module` block), since neither formatter supports a
 * whole-file inline ignore.
 * @param source The formatted generated source.
 */
export function annotateGeneratedFile(source: string): string {
	const ignore = FORMATTER_IGNORE.join('\n');
	const annotated = source
		.replace(/^(import\s+['"]i18next['"])/m, `${ignore}\n$1`)
		.replace(/^(declare\s+module\s+['"]i18next['"])/m, `${ignore}\n$1`);

	return `${GENERATED_FILE_HEADER.join('\n')}\n${annotated}`;
}

/**
 * Recursively walk through the directory and generate the types.
 * @param path The path to walk through.
 * @param namespace The namespace to use.
 */
async function recurse(lines: string[], path: string, namespace: string, options: GenerateOptions) {
	const indent = options.indentation.repeat(3);

	if (options.verbose) console.log(gray(`Reading directory ${DirectoryIcon} ${green(path)}...`));

	const entries = [];
	for await (const dirent of await opendir(path)) {
		entries.push(dirent);
	}
	entries.sort((a, b) => a.name.localeCompare(b.name));

	for (const dirent of entries) {
		const file = join(path, dirent.name);
		if (dirent.isFile()) {
			if (!dirent.name.endsWith('.json')) continue;
			if (options.verbose) console.log(gray(`Processing ${FileIcon} ${green(file)}...`));

			const name = dirent.name.slice(0, -5);
			const key = namespace ? `'${namespace}/${name}'` : name;
			const data = JSON.stringify(JSON.parse(await readFile(file, 'utf8')), undefined, options.indentation);
			lines.push(`${indent}${key}: ${data.replaceAll('\n', `\n${indent}`)};`);
		} else if (dirent.isDirectory()) {
			await recurse(lines, file, namespace ? `${namespace}/${dirent.name}` : dirent.name, options);
		}
	}
}

async function formatWithOxfmt(source: string, destination: string, options: GenerateOptions): Promise<string | undefined> {
	if (!options.oxfmt) return;

	try {
		if (options.verbose) console.log(gray('Loading oxfmt...'));

		const { format } = await import('oxfmt');
		const { code, errors } = await format(destination, source);
		if (errors.length > 0) {
			throw new Error(errors.map((error) => error.message).join('\n'));
		}

		if (options.verbose) console.log(gray('Formatting with oxfmt.'));

		return code;
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		console.warn(
			yellow(
				options.verbose
					? `Failed to format with oxfmt: ${message}. Continuing with unformatted output.`
					: 'Failed to format with oxfmt; install it as a dependency or use --no-oxfmt. Continuing with unformatted output.'
			)
		);
	}

	return undefined;
}

async function formatWithPrettier(source: string, destination: string, options: GenerateOptions): Promise<string | undefined> {
	if (!options.prettier) return;

	try {
		if (options.verbose) console.log(gray('Loading prettier...'));

		const { resolveConfig, format } = await import('prettier');
		const config = await resolveConfig(destination);
		if (options.verbose) console.log(gray(`Formatting with prettier config: ${inspect(config, { colors: true })}`));

		return await format(source, { ...config, filepath: destination });
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		console.warn(
			yellow(
				options.verbose
					? `Failed to format with prettier: ${message}. Continuing with unformatted output.`
					: 'Failed to format with prettier; install it as a dependency or use --no-prettier. Continuing with unformatted output.'
			)
		);
	}

	return undefined;
}

async function formatSource(source: string, destination: string, options: GenerateOptions) {
	return (await formatWithOxfmt(source, destination, options)) ?? (await formatWithPrettier(source, destination, options)) ?? source;
}

export async function generate([source, destination]: string[], options: GenerateOptions) {
	const sourceDirectory = resolve(source);
	const destinationFile = resolve(destination);
	const i1 = options.indentation;
	const i2 = i1.repeat(2);

	if (options.verbose) {
		const lines = [
			`Source: ${DirectoryIcon} ${green(sourceDirectory)}...`,
			`Output: ${FileIcon} ${green(destinationFile)}...`,
			'',
			'Options:',
			`  - Verbose: ${green(options.verbose ? 'yes' : 'no')}`,
			`  - Indentation: ${green(JSON.stringify(options.indentation))}`
		];
		console.log(italic(gray(lines.join('\n'))));
	}

	const lines = ["import 'i18next';", '', "declare module 'i18next' {", `${i1}interface CustomTypeOptions {`, `${i2}resources: {`];

	await recurse(lines, sourceDirectory, '', options);
	lines.push(`${i2}};`, `${i1}}`, '}', '');

	let generatedSource = lines.join('\n');
	generatedSource = await formatSource(generatedSource, destinationFile, options);
	generatedSource = annotateGeneratedFile(generatedSource);

	await mkdir(dirname(destinationFile), { recursive: true });
	await writeFile(destinationFile, generatedSource, 'utf8');
}

interface GenerateOptions {
	verbose: boolean;
	oxfmt: boolean;
	prettier: boolean;
	indentation: string;
}
