name: safe-fetch
org: wolfstar
install: true
packagePath: packages/safe-fetch
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: wolfstar-project/stars-components
gitHostVariant: github
