export { runMain } from './run.js';
export { ExitCode, exitCodeOf, formatError } from './utils/errors.js';
export { cliDiagnostics } from './utils/diagnostics.js';
export type { CliDiagnosticCode } from './utils/diagnostics.js';
export { configDiagnostics, loadStarsConfig } from '@wolfstar/stars-config';
export type { ConfigDiagnosticCode, ResolvedStarsConfig } from '@wolfstar/stars-config';
export { isCIEnvironment, prefersReducedMotion, resolveOutputMode, shouldUseColor } from './utils/output-mode.js';
export type { OutputMode, ResolveOutputModeOptions } from './utils/output-mode.js';
export { THEME_SETTINGS, THEMES, resolveTheme, resolveThemeSetting } from './utils/theme.js';
export type { Theme, ThemeName, ThemeSetting, ThemeToken } from './utils/theme.js';
