import { Piece } from '@sapphire/pieces';
import type { Awaitable, NonNullObject } from '@sapphire/utilities';
import type { AutocompleteInteractionArguments, Interactions } from '../interactions/index.js';
import { CommandRouter } from '../interactions/router/CommandRouter.js';
import { CommandRegistry } from '../interactions/shared/CommandRegistry.js';
import type { Precondition } from '../utils/preconditions.js';

/**
 * The options a command receives, by the full path of the command (`'ping'`, `'stickyroles add'`,
 * `'subscriptions twitch add'`).
 *
 * It is empty on purpose: `stars codegen` fills it, from the builders of the commands the project registers, by
 * augmenting this interface (`codegen.commands` in `stars.config`). {@linkcode Command.OptionsOf} reads it.
 * @since 6.2.0
 * @example
 * ```typescript
 * // src/@types/commands.d.ts (generated)
 * declare module '@wolfstar/http-framework' {
 * 	interface CommandOptionsRegistry {
 * 		'stickyroles add': { role: TransformedArguments.Role; user: TransformedArguments.User };
 * 	}
 * }
 * ```
 */
// oxlint-disable-next-line typescript/no-empty-object-type -- filled by module augmentation
export interface CommandOptionsRegistry {}

export abstract class Command<Options extends Command.Options = Command.Options> extends Piece<Options, 'commands'> {
	/**
	 * The router for the command.
	 * @since 2.0.0
	 */
	public readonly router: CommandRouter<Options>;

	public constructor(context: Command.LoaderContext, options: Options = {} as Options) {
		super(context, options);
		this.registerApplicationCommands?.(new CommandRegistry(this.constructor as typeof Command));
		this.router = new CommandRouter(this);
	}

	/**
	 * Gets the registry for this command.
	 *
	 * @returns The registry for this command, or `null` if it is not registered.
	 */
	public get registry() {
		return this.container.applicationCommandRegistry.get(this.constructor as typeof Command) ?? null;
	}

	/**
	 * Registers this command's application commands imperatively, without relying on decorators.
	 *
	 * @remarks This is invoked once, synchronously, from the base {@linkcode Command} constructor, right before this
	 * command's router is built, and therefore before any subclass field initializers or subclass constructor body have
	 * run. Because of this it must be declared as a method (not a class-field arrow function, which would not yet be
	 * assigned at this point and would be silently skipped) and it must not read subclass instance state, which is still
	 * uninitialized; it should register commands using only the provided `registry`. This matches the static, class-level
	 * nature of the decorators: it is the decorator-free equivalent of {@link RegisterCommand} and its siblings, and a
	 * command should use either this method or the decorators, not both.
	 * @since 3.1.0
	 * @param registry - The registry to register this command's application commands with.
	 * @example
	 * ```typescript
	 * import { Command } from '@wolfstar/http-framework';
	 *
	 * export class UserCommand extends Command {
	 * 	public override registerApplicationCommands(registry: Command.Registry) {
	 * 		registry.registerChatInputCommand((builder) =>
	 * 			builder.setName('ping').setDescription('Runs a network connection test with me')
	 * 		);
	 * 	}
	 *
	 * 	public override chatInputRun(interaction: Command.ChatInputInteraction) {
	 * 		return interaction.reply({ content: 'Pong!' });
	 * 	}
	 * }
	 * ```
	 */
	public registerApplicationCommands?(registry: Command.Registry): unknown;

	/**
	 * Responds to the chat input command for this command
	 *
	 * @param interaction - The interaction to be handled.
	 * @param args - The parsed arguments for this autocomplete interaction.
	 */
	public chatInputRun(interaction: Command.ApplicationCommandInteraction, args: NonNullObject): Awaitable<unknown>;
	public chatInputRun() {
		throw new Error(`The method 'chatInputRun' has not been implemented in ${this.name}.`);
	}

	/**
	 * Responds to an auto completable option for this command
	 *
	 * @param interaction - The interaction to be handled.
	 * @param args - The parsed arguments for this autocomplete interaction.
	 * @returns The response to the autocomplete interaction.
	 */
	public autocompleteRun(interaction: Command.AutocompleteInteraction, args: Command.AutocompleteArguments<any>): Awaitable<unknown>;
	public autocompleteRun() {
		throw new Error(`The method 'autocompleteRun' has not been implemented in ${this.name}.`);
	}
}

export namespace Command {
	export type AutocompleteInteraction = Interactions.Autocomplete;
	export type AutocompleteArguments<T extends object> = AutocompleteInteractionArguments<T>;

	/**
	 * The options of the command at the given path, as generated by `stars codegen` from its builder: `required`
	 * options are not optional, `choices` are a literal union, and every option has the shape the framework resolves it
	 * to at runtime.
	 *
	 * It is not {@linkcode Options}, which is the piece options of the command.
	 * @since 6.2.0
	 * @example
	 * ```typescript
	 * public override chatInputRun(interaction: Command.ChatInputInteraction, options: Command.OptionsOf<'stickyroles add'>) {
	 * 	// options.user.id, options.role.name
	 * }
	 *
	 * public override autocompleteRun(interaction: Command.AutocompleteInteraction, args: Command.AutocompleteArguments<Command.OptionsOf<'stickyroles add'>>) {
	 * 	// args.focused is 'user' | 'role' | null
	 * }
	 * ```
	 */
	export type OptionsOf<K extends keyof CommandOptionsRegistry> = CommandOptionsRegistry[K];

	export type ChatInputInteraction = Interactions.ChatInputCommand;
	export type UserInteraction = Interactions.UserContextMenuCommand;
	export type MessageInteraction = Interactions.MessageContextMenuCommand;

	export type ContextMenuInteraction = Interactions.ContextMenuCommand;
	export type ApplicationCommandInteraction = Interactions.ApplicationCommand;

	export type Interaction = ChatInputInteraction | AutocompleteInteraction | UserInteraction | MessageInteraction;
	export type InteractionData = Interaction['data'];

	export type Registry = CommandRegistry;

	// Piece re-exports
	/** @deprecated Use {@linkcode LoaderContext} instead. */
	export type Context = LoaderContext;
	export type LoaderContext = Piece.LoaderContext<'commands'>;
	export type JSON = Piece.JSON;
	export type LocationJSON = Piece.LocationJSON;
	export interface Options extends Piece.Options {
		/**
		 * The checks to run, in order, before a chat input or context menu method of the command. The first one that
		 * returns an `Err` denies the command: the method is not run and the error is emitted as
		 * `chatInputCommandDenied` or `contextMenuCommandDenied`. Autocomplete is not checked.
		 *
		 * @since 6.3.0
		 * @default []
		 */
		preconditions?: readonly Precondition[];
	}
}
