// This file is automatically generated by `stars codegen`, do not edit it.
/* eslint-disable */
/* oxlint-disable */
// oxfmt-ignore
// prettier-ignore
export {};

// oxfmt-ignore
// prettier-ignore
declare module '@wolfstar/http-framework' {
  interface CommandOptionsRegistry {
    'info': {};
    'math add': {
      left: number;
      right: number;
    };
    'math subtract': {
      left: number;
      right: number;
    };
  }
}
