name: Continuous Delivery

on:
    push:
        branches:
            - main

jobs:
    publish:
        name: Publish Next to npm
        runs-on: ubuntu-latest
        if: github.repository_owner == 'wolfstar-project'
        permissions:
            id-token: write
        strategy:
            fail-fast: false
            matrix:
                package:
                    - env-utilities
                    - http-framework
                    - http-framework-i18n
                    - i18next-backend
                    - influx-utilities
                    - logger
                    - reddit-helpers
                    - safe-fetch
                    - shared-http-pieces
                    - shared-influx-pieces
                    - start-banner
                    - twitch-helpers
                    - weather-helpers
        steps:
            - name: Checkout Project
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
            - name: Use Node.js v20
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: pnpm
                  registry-url: https://registry.npmjs.org/
            - name: Install Dependencies
              run: pnpm install --frozen-lockfile
            - name: Build all packages
              run: pnpm build
            - name: Bump Versions & Publish
              working-directory: packages/${{ matrix.package }}
              run: |
                  pnpm exec cliff-jumper --preid "next.$(git rev-parse --verify --short HEAD)" --skip-changelog

                  pnpm publish --tag next --provenance --access public --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
