name: documentation

on:
    push:
        branches:
            - main
        tags:
            - 'v*'

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    docs:
        uses: wolfstar-project/.github/.github/workflows/reusable-documentation.yml@8f25e7f1f7df3e0611d29384ae43ac8127d83d76 # main
        with:
            project-name: stars-components
            docgen-command: pnpm exec typedoc --options typedoc.json --json docs-output/api.json
            docs-repository: wolfstar-project/docs
        secrets:
            WOLFSTAR_TOKEN: ${{ secrets.WOLFSTAR_TOKEN }}
